### ISSUE TITLE
How to create a subdirectory

### ISSUE THREAD

**Issue by zjcnew** [gsuitedevs/PyDrive#123]
How to create subdirectories and multilevel directories?

**Comment by keliomer** [comment]
A folder/directory in Drive is just a file with the mimetype 'application/vnd.google-apps.folder' by default it will be assigned an ID and you use this ID as the parent ID when creating subdirectories.

Here's an example:

```
from pydrive import auth, drive
#authorize however you want
gauth = auth.GoogleAuth().LocalWebserverAuth()

#create and authorize your drive client object
drive_client = drive.GoogleDrive(gauth)
#Create the folder
# If no parent ID is provided this will automatically go to the root or My Drive 'directory'
top_level_folder = drive_client.CreateFile({'title': 'top_level'})
# Upload the file to your drive
top_level_folder.Upload()
# Grab the ID of the folder we just created
parent_id = parent_folder['id']

# Create a sub-directory
# Make sure to assign it the proper parent ID
child_folder = drive_client.CreateFile({'title': 'level_2', 'parents':[{'id':parent_id}]})
child_folder.Upload()
```

That's it!


[Check out the API documentation](https://developers.google.com/drive/v3/web) it is a huge help in understanding how the metadata for Drive items are used and what you can do with them!

**Comment by zjcnew** [comment]
Your answer perfectly solved my problem, thank you very much.


________________________________
发件人: Keliomer <notifications@github.com>
发送时间: 2018年3月28日 8:05
收件人: gsuitedevs/PyDrive
抄送: 从删库到跑路的自我修养; Author
主题: Re: [gsuitedevs/PyDrive] How to create a subdirectory (#123)


A folder/directory in Drive is just a file with the mimetype 'application/vnd.google-apps.folder' by default it will be assigned an ID and you use this ID as the parent ID when creating subdirectories.

Here's an example:

from pydrive import auth, drive
#authorize however you want
gauth = auth.GoogleAuth().LocalWebserverAuth()

#create and authorize your drive client object
drive_client = drive.GoogleDrive(gauth)
#Create the folder
# If no parent ID is provided this will automatically go to the root or My Drive 'directory'
top_level_folder = drive_client.CreateFile({'title': 'top_level'})
# Upload the file to your drive
top_level_folder.Upload()
# Grab the ID of the folder we just created
parent_id = parent_folder['id']

# Create a sub-directory
# Make sure to assign it the proper parent ID
child_folder = drive_client.CreateFile({'title': 'level_2', 'parents':[{'id':parent_id}]})
child_folder.Upload()


That's it!

Check out the API documentation<https://developers.google.com/drive/v3/web> it is a huge help in understanding how the metadata for Drive items are used and what you can do with them!

―

**Comment by arlmath** [comment]
file1 = drive.CreateFile({'title':"folder_name","parents":[{'id':"folder_id"}],'mimeType':"application/vnd.google-apps.folder"})
