### ISSUE TITLE
Changing a file so that it can't be downloaded (["capabilities"]["canDownload"]=false)

### ISSUE THREAD

**Issue by nival999** [gsuitedevs/PyDrive#141]
I have tried setting the file metadata both before upload and after upload, and the capabilities metadata still can't be accessed. 
From the documentation:

```
Handling special metadata

Not all metadata can be set with the methods described above. (It's about to give me the answer!) PyDrive gives you access to the metadata of an object through file_object.FetchMetadata(). (Access, okay!) This function has two optional parameters: fields and fetch_all (Cool!)

file1 = drive.CreateFile({'id': '<some file ID here>'})

# Fetches all basic metadata fields, including file size, last modified etc.
file1.FetchMetadata()

# Fetches all metadata available.
file1.FetchMetadata(fetch_all=True)
# Two read examples...
# Fetches the 'permissions' metadata field.
file1.FetchMetadata(fields='permissions')
# Three read examples....

# You can update a list of specific fields like this:
file1.FetchMetadata(fields='permissions,labels,mimeType')
#What? This didn't update the data at all. 

For more information on available metadata fields have a look at the official documentation.

```

I am pretty sure there is supposed to be an example somewhere here of "setting" these advanced metadata fields, judging by the segue in the documentation, and then the line: 
```
# You can update a list of specific fields like this:
file1.FetchMetadata(fields='permissions,labels,mimeType')

```
Is there a way to update the capabilities permission? And not just read from it? Also, are there any more endpoints to read and parse the MetaData JSON? I really enjoy learning about different ways to parse JSON in my spare time.

**Comment by sqrrrl** [comment]
Capabilities are read-only fields and are a summary of what the current user is allowed to do to the file. The values will change based on the user and the level of access they have to a file, the file type, etc. You can set *other* properties to affect those, such as copyRequiresWriterPermission, writersCanShare, etc
