### ISSUE TITLE
Get file object or stream to download

### ISSUE THREAD

**Issue by panchipanchi** [gsuitedevs/PyDrive#173]
GetContentFile writes the file's content to HDD
if you're reading large files and only interested in getting certain data from it, this is inconvenient and requires unecesssary read/write operations. How about a GetContent() method to return a file stream object, so we can read() what we want from it....?
I've seen it done with the regular API here:
https://youtu.be/-7YH6rdR-tk?t=573

if there is already a way to do it with pydrive,  let me know
i've tried fetchcontent, but returns None

**Comment by alexacallmebaka** [comment]
How did you end up doing this?

**Comment by alexacallmebaka** [comment]
How did you end up doing this? I am having the same problem where FetchContent returns None.

**Comment by shcheklein** [comment]
@alexacallmebaka this is solved in the [PyDrive2](https://github.com/iterative/PyDrive2), example is here https://github.com/iterative/dvc/blob/master/dvc/tree/gdrive.py#L376-L391

**Comment by alexacallmebaka** [comment]
@shcheklein I have download and installed PyDrive2, but FetchContent still returns none. I would like to get the content of a file from Google Drive as an in-memory buffer, such as a BytesIO object.

**Comment by shcheklein** [comment]
The example above is using `GetContentFile`. You can pass any writable object to it (it can be in-memory buffer).

If you want to get a file-like interface, give this one: https://github.com/iterative/PyDrive2/blob/master/pydrive2/files.py#L395

a try.

**Comment by alexacallmebaka** [comment]
Thanks! I figured it out. For anyone reading this, it's not exactly clear how to use this object correctly, so here is an example:
```
from io import BytesIO
 with BytesIO() as buffer:
      for chunk in file.GetContentIOBuffer():
           buffer.write(chunk)
```
