### ISSUE TITLE
AttributeError: module 'googleapiclient' has no attribute '__version__'

### ISSUE THREAD

**Issue by dmoneyliu** [gsuitedevs/PyDrive#196]
Hello, I believe google-api-python-client 1.8.1 has made the imported package apiclient obsolete, the proposed solution is to import googleapiclient instead, as prescribed here: https://stackoverflow.com/questions/61334085/breaking-change-for-google-api-python-client-1-8-1-attributeerror-module-goo

**Comment by shcheklein** [comment]
It should be fixed in the maintained PyDrive2, please give it a try.

**Comment by dmoneyliu** [comment]
@shcheklein great, thank you
